# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pal < Formula
  desc ""
  homepage "https://github.com/jaytyrrell13/pal"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jaytyrrell13/pal/releases/download/v0.2.0/pal_Darwin_arm64.tar.gz"
      sha256 "6121a5e1243ce88b573345137044fbe30b4df4a4393f265af17e90400f7f2eed"

      def install
        bin.install "pal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaytyrrell13/pal/releases/download/v0.2.0/pal_Darwin_x86_64.tar.gz"
      sha256 "9f95feb0824e8a76421f99187aa2d34fa979534688904e34413be667f595aacb"

      def install
        bin.install "pal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaytyrrell13/pal/releases/download/v0.2.0/pal_Linux_arm64.tar.gz"
      sha256 "d20c448b04dcc8069db9234a37a454b2cc6e539808634d56f6a5a5028d358c83"

      def install
        bin.install "pal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaytyrrell13/pal/releases/download/v0.2.0/pal_Linux_x86_64.tar.gz"
      sha256 "3f6bc81670d2f167d95d41c35dd5d38bd85305834d7ae514fec3e57d82e3963f"

      def install
        bin.install "pal"
      end
    end
  end
end
