# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pal < Formula
  desc ""
  homepage "https://github.com/jaytyrrell13/pal"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaytyrrell13/pal/releases/download/v0.7.0/pal_Darwin_x86_64.tar.gz"
      sha256 "65e49cabdad2691686a0e13b73036da82c28b01e5440d773cc634c889b8d2737"

      def install
        bin.install "pal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaytyrrell13/pal/releases/download/v0.7.0/pal_Darwin_arm64.tar.gz"
      sha256 "73ff964570156dae2531b54fd6b16b0583f5e63dfed7ae701008927b21525aed"

      def install
        bin.install "pal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jaytyrrell13/pal/releases/download/v0.7.0/pal_Linux_x86_64.tar.gz"
      sha256 "6a1cf955ec8465fda1130dad416edb7fe4a08a8087598b141762e4ca1e3a2564"

      def install
        bin.install "pal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaytyrrell13/pal/releases/download/v0.7.0/pal_Linux_arm64.tar.gz"
      sha256 "ecd0df9a6eebcf2c1f03f737f7bf0a41d75a0947bb9f8c38e38bedf9468d9d28"

      def install
        bin.install "pal"
      end
    end
  end
end
